spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=branch_334
    username: try_334
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  thymeleaf:
    check-template: false
    check-template-location: false
  security:
    user:
      name: lst
      password: 123456
server:
  port: 8888
